app/models/manageiq/providers/cisco_intersight/inventory/parser/physical_infra_manager.rb, app/models/manageiq/providers/cisco_intersight/physical_infra_manager/operations/power.rb, spec/models/manageiq/providers/cisco_intersight/physical_infra_manager/refresher_spec.rb
This PR resolves #11.
Implemented methods for all ManageIQ power functions except `restart_to_sys_setup`, which is not supported by Intersight.
Intersight-managed servers can now be powered on, shut down, restarted, etc. Note that some servers might have different management modes (e.g. UCSM) and their power cannot be configured through the Intersight API.
Beside adding power operations functions, also changed `parser/physical_infra_manager.rb` to observe `oper_power_state` attribute representing the actual power state instead of `admin_power_state` (which represents the requested state).
Also removed `.idea` directory used by IntelliJ IDE (RubyMine).
=> Add power management

.gitignore, app/models/manageiq/providers/cisco_intersight/inventory/collector/physical_infra_manager.rb, app/models/manageiq/providers/cisco_intersight/inventory/parser/physical_infra_manager.rb, app/models/manageiq/providers/cisco_intersight/inventory/persister/definitions/physical_infra_collections.rb, app/models/manageiq/providers/cisco_intersight/physical_infra_manager/physical_switch.rb, app/models/manageiq/providers/cisco_intersight/physical_infra_manager/physical_switch_network_ports.rb, spec/models/manageiq/providers/cisco_intersight/physical_infra_manager/refresher_spec.rb, spec/spec_helper.rb
This PR includes new server and switch physical infrastructure into the inventory.
To be more specific, the following changes have been made regarding inventory:
Minor changes in inventory in general (such as parse new data in already existing collections)
- Include switches' details (into the collection physical_switch_details)
- Include switch's hardware (into the collection physical_switch_hardwares)
- Include switch's firmware (into the collection physical_switch_firmwares)
- Include switch's ports in inventory (into the collection physical_switch_network_ports).
- switch's networks (into the collection physical_switch_networks)
- Include physical switches (into the collection physical_switches)
**Additional comments for persister collection physical_switch_network_ports and …
=> Enhance Inventory's features (#1)

app/models/manageiq/providers/cisco_intersight/inventory/collector/physical_infra_manager.rb, app/models/manageiq/providers/cisco_intersight/inventory/parser/physical_infra_manager.rb, app/models/manageiq/providers/cisco_intersight/inventory/persister/definitions/physical_infra_collections.rb, spec/models/manageiq/providers/cisco_intersight/physical_infra_manager/refresher_spec.rb
This PR is a follow-up PR to https://github.com/ManageIQ/manageiq-providers-cisco_intersight/pull/35. It address code style comments in the original pull request, made by @agrare. 
To summarize, the following changes have been made:
- [Replace find_by with index_by function for the sake of efficiency](https://github.com/ManageIQ/manageiq-providers-cisco_intersight/commit/59d87818f76334ed23b85455a1c31cd1af69aa95)
- [Renamed function build_physical_servers to singular](https://github.com/ManageIQ/manageiq-providers-cisco_intersight/commit/91a3880f2fca3f4b9b35d347987c8c1d2840a1f7)
- [Renamed function build_physical_server_computer_systems to singular](https://github.com/ManageIQ/manageiq-providers-cisco_intersight/commit/8e00ad36cee35dfd30a05a073a32856f96ccfe90)
- [Removed :type attribute in …
=> Enhance Inventory's features - follow-up

app/helpers/manageiq/providers/cisco_intersight/toolbar_overrides/physical_server_center.rb, app/helpers/manageiq/providers/cisco_intersight/toolbar_overrides/physical_servers_center.rb, app/models/manageiq/providers/cisco_intersight/inventory/parser/physical_infra_manager.rb, app/models/manageiq/providers/cisco_intersight/physical_infra_manager/operations.rb, app/models/manageiq/providers/cisco_intersight/physical_infra_manager/operations/lifecycle.rb
This commit adds support for decommission and recommission lifecycle
operations of Cisco Intersight provider.
=> Add support for lifecycle operations

app/models/manageiq/providers/cisco_intersight/inventory/parser/physical_infra_manager.rb, spec/models/manageiq/providers/cisco_intersight/physical_infra_manager/refresher_spec.rb
This PR fixes server-chasses relationship.
In the code below, server is object, obtained from the Intersight gem - it belongs to class `IntersightClient::ComputePhysicalSummary`.
On the Intersight side, server's attribute `equipment_chassis` was removed, making value `server.equipment_chassis.moid` equal to `nil` and consequently, making `physical_chassis` equal to `nil` so there was no relationship between servers and chassis.
Instead, I parsed server's `parent` value and obtained parent's `moid` (unique ID for Intersight objects).
=> Fix server-chassis relationship

app/models/manageiq/providers/cisco_intersight/inventory/collector/physical_infra_manager.rb, app/models/manageiq/providers/cisco_intersight/inventory/parser/physical_infra_manager.rb, spec/models/manageiq/providers/cisco_intersight/physical_infra_manager/refresher_spec.rb, spec/vcr_cassettes/ManageIQ_Providers_CiscoIntersight_PhysicalInfraManager_Refresher/refresh/will_perform_a_full_refresh.yml
This PR changes attribute `:name` for collection `physical_switches` in collector. To summarize changes with this PR:
- _Parser_: Before, name stored distinguished name (called `dn`) of Intersight object `NetworkElements`. Now, it stores `name` of Intersight object `NetworkElementSummary`. 
- _Collector_: `NetworkElements` and `NetworkElementSummary` have the same `moid`s ( = unique ID on the intersight side), so I add helper function `get_network_element_summary_by_moid`. In parser, `NetworkElementSummary` is obtained from `NetworkElements` (I store these two objects in variables `network_element` and `network_element_summary`, respectively)
=> Changed the name of physical switches

app/models/manageiq/providers/cisco_intersight/inventory/collector/physical_infra_manager.rb, app/models/manageiq/providers/cisco_intersight/manager_mixin.rb, app/models/manageiq/providers/cisco_intersight/physical_infra_manager/operations/lifecycle.rb, app/models/manageiq/providers/cisco_intersight/physical_infra_manager/operations/power.rb, spec/models/manageiq/providers/cisco_intersight/physical_infra_manager_spec.rb
Rather than setting `IntersightClient::Configuration.@@default` we can initialize a `IntersightClient::Configuration` object, set the key and key_id, and build an `IntersightClient::ApiClient` based on that
Fixes https://github.com/ManageIQ/manageiq-providers-cisco_intersight/issues/44
=> Refactor IntersightClient ApiClient usage

app/models/manageiq/providers/cisco_intersight/manager_mixin.rb
The refactor introduced a small bug in the `with_provider_connection` as
it required a file based on the `:service`. In the code that actually
used this, this did not work.
This patch removes the unnecessary `require` statement.
=> Fix Cisco Intersight connection

app/helpers/manageiq/providers/cisco_intersight/toolbar_overrides/physical_server_center.rb, app/javascript/components/server-profile-form.js, app/javascript/components/server-profile-form.schema.js, app/javascript/packs/component-definitions-common.js, app/models/manageiq/providers/cisco_intersight/physical_infra_manager/assign_server_profile_button.rb, package.json
This commit adds support for three operations on top of server profiles:
assign server profile, unassign server profile and deploy server (i.e.
activate the assigned server profile for a chosen server). It extends
the toolbar for Intersight as well as adds a new dialog used to select
relecant information and request these operations.
Screenshots below show the effects.
Toolbar for Cisco Intersight Physical server:
Assign Server Profile dialog
Deploy server profile:
Unassign server profile:
=> Add server profile operations' dialogs

app/models/manageiq/providers/cisco_intersight/inventory/parser/physical_infra_manager.rb, spec/models/manageiq/providers/cisco_intersight/physical_infra_manager/refresher_spec.rb
This PR adds port_status for switch's network ports and updates the tests accordingly. 
port_status will always hold just value of either `Enabled` or `Disabled`.
=> Fix Network Port's port_status

app/models/manageiq/providers/cisco_intersight/physical_infra_manager/physical_server_profile.rb
Fixes a bug extracting model translations from manageiq:
```
% be rake locale:update_all
** ManageIQ master, codename: Oparin
** Using session_store: ActionDispatch::Session::MemoryStore
** ManageIQ master, codename: Oparin
writing model translations to: /Users/joerafaniello/Code/manageiq/locale/model_attributes.rb
rake aborted!
ArgumentError: wrong number of arguments (given 0, expected 1)
/Users/joerafaniello/.gem/ruby/2.7.5/bundler/gems/manageiq-providers-cisco_intersight-948ac7a302da/app/models/manageiq/providers/cisco_intersight/physical_infra_manager/physical_server_profile.rb:3:in `display_name'
```
Note, all other provider's `display_name` method provide a default number for the argument so I copied that pattern.
=> Provide default for display_name matching other provider patterns

app/models/manageiq/providers/cisco_intersight/physical_infra_manager/event_catcher/stream.rb
This PR is a follow-up to https://github.com/ManageIQ/manageiq-providers-cisco_intersight/pull/55. Last time, polling did not take into consideration historical events and was not able to fetch them. This PR changes this by redefining variable since in the polling function.
=> Redefine `since` in method poll

app/helpers/manageiq/providers/cisco_intersight/toolbar_overrides/physical_servers_center.rb
This PR renames button on server view from 'Cisco Intersight' to 'Intersight'
=> Renamed button on server view from 'Cisco Intersight' to 'Intersight'

app/helpers/manageiq/providers/cisco_intersight/toolbar_overrides/physical_servers_center.rb
This PR adds buttons for deploying and unassigning server profiles when viewing multiple physical servers in UI (this is done by going to "Physical Infrastructure" --> "Providers" --> Choosing a specific provider --> "Physical Servers").
Physical servers view before the the change:
Physical servers view after the the change:
=> Add buttons for deploying and unassigning server profiles in physical servers view

app/models/manageiq/providers/cisco_intersight/manager_mixin.rb, spec/models/manageiq/providers/cisco_intersight/physical_infra_manager_spec.rb
Fixes #66
Related to https://github.com/xlab-si/intersight-sdk-ruby/issues/13
Delay loading the intersight client saves time booting the rails application
along with memory and required files:
% time bundle exec rails r 'ManageIQ::Providers::CiscoIntersight::ManagerMixin'
Before:
bundle exec rails r 'ManageIQ::Providers::CiscoIntersight::ManagerMixin'  15.39s user 6.63s system 92% cpu 23.869 total
After:
bundle exec rails r 'ManageIQ::Providers::CiscoIntersight::ManagerMixin'  4.86s user 2.28s system 98% cpu 7.215 total
=> Delay load the large intersight client

manageiq-providers-cisco_intersight.gemspec
Before, with 0.1.3:
```
% ruby -e 'require "sys/proctable"; memory = Sys::ProcTable.ps(:pid => Process.pid).rss; time = Time.now; require "intersight_client"; puts "Require time: #{Time.now - time}"; GC.start; puts "memory growth: #{Sys::ProcTable.ps(:pid => Process.pid).rss - memory}"; puts "Version: #{IntersightClient::VERSION}"'
Require time: 7.306528
memory growth: 392_871_936
Version: 0.1.3
```
After, with 0.1.4:
```
% ruby -e 'require "sys/proctable"; memory = Sys::ProcTable.ps(:pid => Process.pid).rss; time = Time.now; require "intersight_client"; puts "Require time: #{Time.now - time}"; GC.start; puts "memory growth: #{Sys::ProcTable.ps(:pid => Process.pid).rss - memory}"; puts "Version: #{IntersightClient::VERSION}"'
Require time: 0.182657
memory growth: 20_295_680
Version: 0.1.4 …
```
=> Set minimum client version to a much faster and leaner 0.1.4

manageiq-providers-cisco_intersight.gemspec
0.1.5 includes xlab-si/intersight-sdk-ruby#17 which lowers the disk space
usage of the gem by ~76MB
@agrare Please review.
=> Bump minimum version of intersight_client to 0.1.5

app/models/manageiq/providers/cisco_intersight/inventory/collector/physical_infra_manager.rb, app/models/manageiq/providers/cisco_intersight/inventory/parser/physical_infra_manager.rb, app/models/manageiq/providers/cisco_intersight/inventory/persister/definitions/physical_infra_collections.rb, app/models/manageiq/providers/cisco_intersight/physical_infra_manager.rb, app/models/manageiq/providers/cisco_intersight/physical_infra_manager/ems_refresh_workflow.rb, app/models/manageiq/providers/cisco_intersight/physical_infra_manager/physical_server_profile_template.rb, spec/vcr_cassettes/ManageIQ_Providers_CiscoIntersight_PhysicalInfraManager_Refresher/refresh/will_perform_a_full_refresh.yml
Add the physical_server_profile_templates to Physical Infra Manager.
=> add physical server profile template

app/models/manageiq/providers/cisco_intersight/physical_infra_manager/physical_server_profile_template.rb
The provider name should be `Cisco Intersight` not `CiscoIntersight` as this is user facing
=> Fix display_name for PhysicalServerProfileTemplate

app/models/manageiq/providers/cisco_intersight/manager_mixin.rb
https://github.com/ManageIQ/manageiq/issues/22845
=> Add zone_id to provider validationDependencies

app/models/manageiq/providers/cisco_intersight/inventory.rb, app/models/manageiq/providers/cisco_intersight/inventory/collector.rb, app/models/manageiq/providers/cisco_intersight/inventory/parser.rb, app/models/manageiq/providers/cisco_intersight/inventory/persister.rb, app/models/manageiq/providers/cisco_intersight/physical_infra_manager.rb, app/models/manageiq/providers/cisco_intersight/physical_infra_manager/event_catcher.rb, app/models/manageiq/providers/cisco_intersight/physical_infra_manager/firmware_update_task.rb, app/models/manageiq/providers/cisco_intersight/physical_infra_manager/metrics_collector_worker.rb, app/models/manageiq/providers/cisco_intersight/physical_infra_manager/operations.rb, app/models/manageiq/providers/cisco_intersight/physical_infra_manager/physical_server.rb, app/models/manageiq/providers/cisco_intersight/physical_infra_manager/provision.rb, app/models/manageiq/providers/cisco_intersight/physical_infra_manager/refresh_worker.rb
Zeitwerk completely removes the need for these methods. See also: https://github.com/ManageIQ/manageiq/pull/22854
=> Drop require_nested and include_concern

app/models/manageiq/providers/cisco_intersight/manager_mixin.rb, spec/models/manageiq/providers/cisco_intersight/physical_infra_manager_spec.rb
NOTE this will work without a default_endpoint at all but we should create a schema migration to set the default values for existing providers
Fixes https://github.com/ManageIQ/manageiq-providers-cisco_intersight/issues/103
=> Allow overriding the Cisco Intersight ApiClient scheme/host/verify_ssl for on-premise intersight controller

app/models/manageiq/providers/cisco_intersight/manager_mixin.rb, spec/models/manageiq/providers/cisco_intersight/physical_infra_manager_spec.rb
The openapi generated `ApiClient`/`Configuration` classes have a way to to pass scheme, host, and base_path but they are ignored and `Configuration#server_settings` is used unless server_index is set to `nil`
=> Fix URL override not being used for API calls
